import {AuthenticatedProvider} from './data-provider.js';
import {configurarPushNativo} from './native-push.js';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=d=>{if(!d)return'';const[y,m,a]=String(d).slice(0,10).split('-');return`${a}/${m}/${y}`},hrs=m=>`${Math.floor(Math.abs(Number(m||0))/60)}h${String(Math.abs(Number(m||0))%60).padStart(2,'0')}`,norm=v=>String(v??'').trim().toUpperCase().normalize('NFD').replace(/[\u0300-\u036f]/g,''),hoje=()=>new Date().toISOString().slice(0,10);
let provider=new AuthenticatedProvider(),catalog=[],quadro=null,editPermuta=0;
function view(id){document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('hidden',x.dataset.view!==id));document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.go===id));if(id==='inicio')carregarQuadro();if(id==='escala')relatorio();if(id==='permutas')permutas();if(id==='banco')banco();if(id==='viaturas')viaturas();if(id==='acessos')outros();if(id==='avisos')avisos()}
function acesso(m){if(provider.gestor())return true;if(m==='escalas')return provider.pode('escalas')||provider.pode('relatorios');return provider.pode(m)}
function permissoes(){document.querySelectorAll('nav button').forEach(b=>{let ok=true;if(b.dataset.go==='escala')ok=acesso('escalas');if(b.dataset.go==='viaturas')ok=acesso('abastecimentos')||acesso('manutencoes');if(b.dataset.go==='permutas')ok=acesso('permutas');if(b.dataset.go==='banco')ok=acesso('banco_horas');b.classList.toggle('hidden',!ok)})}
function perfil(){const s=provider.session||{};$('perfilNome').textContent=s.nome||'';$('perfilCargo').textContent=s.cargo||s.role||'';$('perfilUsuario').textContent=s.usuario||s.username||'';$('perfilRole').textContent=s.role||'gcm';$('listaPermissoes').innerHTML=provider.controleTotal()?'<span class="badge">CONTROLE TOTAL</span>':provider.permissoesEfetivas().map(p=>`<span class="badge">${esc(p.modulo)} · ${esc(p.nivel)}</span>`).join('')}
async function carregarQuadro(){try{const d=await provider.quadro($('quadroData').value||hoje());quadro=d;[['qAtivos',d.efetivo?.ativos],['qAfastados',d.efetivo?.afastados],['qFerias',d.efetivo?.feristas],['qServicoA',d.efetivo?.servicoA],['qServicoB',d.efetivo?.servicoB],['qViaturasTotal',d.viaturas?.total],['qViaturasDisponiveis',d.viaturas?.disponivel],['qViaturasUso',d.viaturas?.emUso],['qViaturasBaixadas',d.viaturas?.baixadas],['qViaturasManut',d.viaturas?.manutencao],['qPostos',d.postos?.cobertos]].forEach(([i,v])=>$(i).textContent=v||0);$('qAviso').textContent='Quadro Operacional atualizado.'}catch(e){$('qAviso').textContent=e.message}}
function detalhe(c,t){const[g,k]=c.split('.'),a=g==='efetivo'?quadro?.efetivo?.detalhes?.[k]:g==='viaturas'?quadro?.viaturas?.detalhes?.[k]:quadro?.postos?.detalhamento||[];$('quadroModalTitulo').textContent=t;$('quadroModalLista').innerHTML=(a||[]).map(x=>`<div class="item"><strong>${esc(x.nome||'-')}</strong><span>${esc(x.complemento||'')}</span></div>`).join('')||'<div class="empty">Nenhum registro.</div>';$('quadroModal').classList.remove('hidden')}
const nome=x=>x.nome_guerra||x.hist_guarda_nome_guerra||x.guarda_nome||x.guarda||'GCM',posto=x=>String(x.posto_nome||x.hist_posto_nome||x.posto||'').trim(),hor=x=>{const i=String(x.horario_inicio||x.hist_horario_inicio||'').slice(0,5),f=String(x.horario_fim||x.hist_horario_fim||'').slice(0,5);return i&&f?`${i} às ${f}`:String(x.turno).toUpperCase()==='B'?'19:00 às 07:00':'07:00 às 19:00'};
function datas(i,f){const a=[];if(!i||!f)return a;for(let d=new Date(i+'T00:00:00Z'),z=new Date(f+'T00:00:00Z');d<=z;d.setUTCDate(d.getUTCDate()+1))a.push(d.toISOString().slice(0,10));return a}
function relatorio(){const all=provider.escalas(),gv=$('escalaGcm').value,pv=$('escalaPosto').value;$('escalaGcm').innerHTML='<option value="">Todos os GCMs</option>'+[...new Set(all.map(nome))].sort().map(x=>`<option>${esc(x)}</option>`).join('');$('escalaPosto').innerHTML='<option value="">Todos os postos</option>'+[...new Set(all.map(posto).filter(Boolean))].sort().map(x=>`<option>${esc(x)}</option>`).join('');$('escalaGcm').value=gv;$('escalaPosto').value=pv;const i=$('escalaIni').value,f=$('escalaFim').value;if(!i||!f)return;const g=$('escalaGcm').value,p=$('escalaPosto').value,h=$('escalaHorario').value,r=all.filter(x=>{const d=String(x.data).slice(0,10);return d>=i&&d<=f&&(!g||norm(nome(x))===norm(g))&&(!p||norm(posto(x))===norm(p))&&(!h||hor(x)===h)}),ds=datas(i,f),map=new Map();for(const x of r){const k=posto(x)+'|'+hor(x);if(!map.has(k))map.set(k,{p:posto(x),h:hor(x),d:new Map()});const a=map.get(k).d.get(x.data)||[];a.push(nome(x));map.get(k).d.set(x.data,a)}$('cabecalhoMatrizMobile').innerHTML='<th>POSTO / HORÁRIO</th>'+ds.map(x=>`<th>${fmt(x)}</th>`).join('');$('resultadoMatrizMobile').innerHTML=[...map.values()].map(x=>`<tr><th><b>${esc(x.p)}</b><span>${esc(x.h)}</span></th>${ds.map(d=>`<td>${(x.d.get(d)||[]).map(n=>`<b>${esc(n)}</b>`).join('<br>')||'—'}</td>`).join('')}</tr>`).join('')||'<tr><td>Nenhuma escala encontrada.</td></tr>';$('escalaInfo').textContent=`${r.length} registro(s) · ${fmt(i)} a ${fmt(f)}`}
function st(r){let s=String(r.status||'').toUpperCase(),q=String(r.resposta||'').toUpperCase();if(q.includes('RECUS'))return'RECUSADA';if(q.includes('APROV'))return'APROVADA';return s==='PENDENTE_DESKTOP'?'PENDENTE':s}
function banco(){const b=provider.bancoHoras().filter(x=>String(x.status||'ATIVO').toUpperCase()==='ATIVO');let a=0,c=0,d=0;for(const x of b){const sg=String(x.natureza).toUpperCase()==='DEBITO'?-1:1,m=Number(x.minutos||0);if(sg<0)d+=m;else String(x.classe)==='100'?c+=m:a+=m}$('bh50').textContent=hrs(a);$('bh100').textContent=hrs(c);$('bhDeb').textContent=hrs(d);$('bhSaldo').textContent=hrs(a+c-d);$('listaBanco').innerHTML=b.slice(0,40).map(x=>`<div class="item"><small>${fmt(x.data_fato)} · ${esc(x.classe||'50')}%</small><strong>${esc(x.tipo||x.origem||'Movimentação')}</strong><span>${String(x.natureza).toUpperCase()==='DEBITO'?'-':'+'}${hrs(x.minutos)}</span></div>`).join('')||'<div class="empty">Sem movimentações.</div>';$('listaCorrecoes').innerHTML=provider.actionRequests().filter(x=>x.tipo==='BANCO_HORAS_CORRECAO').map(r=>`<div class="item"><small>${fmt(r.payload?.data_servico)} · ${hrs(r.payload?.minutos_solicitados)}</small><strong>${esc(r.payload?.descricao||'Solicitação')}</strong><span>${esc(st(r))}</span>${r.resposta?`<small>${esc(r.resposta)}</small>`:''}</div>`).join('')||'<div class="empty">Nenhuma solicitação.</div>'}
async function candidatos(){if(!$('pmData').value)return;try{const r=await provider.call('permutation_candidates',{data:$('pmData').value,turno:$('pmTurno').value,servico_extra:Number($('pmExtra').value)});$('pmSubstituto').innerHTML='<option value="">Selecione</option>'+(r.candidates||[]).map(x=>`<option value="${x.guarda_id}">${esc(x.nome_guerra)}</option>`).join('')}catch(e){$('pmMsg').textContent=e.message}}
function permutas(){const req=provider.actionRequests().filter(x=>x.tipo==='PERMUTA'),hist=provider.permutas();$('listaPermutasSolicitadas').innerHTML=[...req.map(r=>{const s=st(r),p=r.payload||{};return`<div class="item"><small>${fmt(p.data)} · Turno ${esc(p.turno||'-')}</small><strong>Substituto: ${esc(p.substituto_nome||'')}</strong><span>${esc(s)}</span>${r.resposta?`<small>${esc(r.resposta)}</small>`:''}${s==='PENDENTE'?`<button class="mini" data-edit="${r.id}">Editar</button> <button class="mini" data-del="${r.id}">Excluir</button>`:''}</div>`}),...hist.map(p=>`<div class="item"><small>${fmt(p.data)} · Turno ${esc(p.turno)}</small><strong>${esc(p.substituido_nome||'GCM')} → ${esc(p.substituto_nome||'GCM')}</strong><span>${esc(p.status||'')}</span>${p.motivo_decisao?`<small>${esc(p.motivo_decisao)}</small>`:''}</div>`)].join('')||'<div class="empty">Nenhuma permuta.</div>';document.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{if(confirm('Excluir solicitação pendente?')){await provider.cancelPermutaRequest(Number(b.dataset.del));permutas()}});document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const r=req.find(x=>Number(x.id)===Number(b.dataset.edit)),p=r.payload||{};editPermuta=r.id;$('pmData').value=p.data||'';$('pmTurno').value=p.turno||'A';$('pmExtra').value=String(p.servico_extra||0);$('pmObs').value=p.observacao||'';$('pmTermo').checked=!!p.concordou_termo;$('pmCancelarEdicao').classList.remove('hidden');candidatos()})}
function viaturas(){const a=[];if(acesso('abastecimentos'))a.push(['abastecimentos','Abastecimento']);if(acesso('manutencoes'))a.push(['manutencoes','Manutenção']);if(provider.gestor())a.push(['relatorios_frota','Relatórios da Frota']);const box=$('listaViaturasDinamico');if(box){box.innerHTML=a.map(([m,n])=>`<article class="module-card"><strong>${n}</strong><button class="mini" data-mod="${m}">Abrir</button></article>`).join('')}}
const ocultos=new Set(['dashboard','escalas','relatorios','banco_horas','permutas','abastecimentos','manutencoes','relatorios_frota']);function outros(){$('listaModulos').innerHTML=provider.modulosAutorizados().filter(m=>!ocultos.has(m.id)).map(m=>`<article class="module-card"><div><strong>${esc(m.nome)}</strong><small>${esc(m.descricao)}</small></div><span class="level">${esc(m.nivel)}</span></article>`).join('')||'<div class="empty">Nenhum outro módulo autorizado.</div>'}
function avisos(){$('mensagemComandoCard').classList.toggle('hidden',!provider.gestor());$('listaAvisos').innerHTML=provider.notifications().map(n=>`<div class="item"><small>${esc(n.tipo||'AVISO')} · ${esc(n.criado_em||'')}</small><strong>${esc(n.titulo||'Aviso')}</strong><span>${esc(n.mensagem||'')}</span></div>`).join('')||'<div class="empty">Sem notificações.</div>'}
async function catalogo(){try{catalog=await provider.entityCatalog()}catch{}}
async function abrirModulo(m){view('online');const c=catalog.filter(x=>x.modulo===m);$('onlineEntidades').innerHTML=c.map(x=>`<article class="module-card" data-ent="${x.entity}"><strong>${esc(x.titulo)}</strong></article>`).join('');document.querySelectorAll('[data-ent]').forEach(e=>e.onclick=async()=>{const r=await provider.entityList(e.dataset.ent);$('onlineTitulo').textContent=r.catalog?.titulo||'';$('onlineEntidades').closest('.card').classList.add('hidden');$('onlineRegistrosCard').classList.remove('hidden');$('onlineRegistros').innerHTML=(r.records||[]).map(z=>`<div class="item">${Object.entries(z.data||{}).filter(([k])=>!/(^id$|_id$|dados)/i.test(k)).slice(0,12).map(([k,v])=>`<small><b>${esc(k)}</b>: ${esc(typeof v==='object'?JSON.stringify(v):v)}</small>`).join('')}</div>`).join('')})}
async function iniciar(){const s=await provider.restore();if(!s)return;$('loginTela').classList.add('hidden');$('appTela').classList.remove('hidden');$('quadroData').value=hoje();perfil();permissoes();banco();permutas();avisos();outros();await catalogo();await carregarQuadro();configurarPushNativo(provider).catch(()=>{})}
$('loginForm').onsubmit=async e=>{e.preventDefault();try{await provider.login($('loginUsuario').value,$('loginSenha').value);await iniciar()}catch(x){$('loginErro').textContent=x.message}};$('sair').onclick=async()=>{await provider.logout();location.reload()};document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>view(b.dataset.go));$('quadroData').onchange=carregarQuadro;document.querySelectorAll('[data-quadro-detail]').forEach(b=>b.onclick=()=>detalhe(b.dataset.quadroDetail,b.dataset.title));$('quadroModalFechar').onclick=()=>$('quadroModal').classList.add('hidden');$('escalaGerar').onclick=relatorio;$('escalaLimpar').onclick=()=>{$('escalaGcm').value='';$('escalaPosto').value='';$('escalaHorario').value='';relatorio()};
$('formBancoCorrecao').onsubmit=async e=>{e.preventDefault();const m=Number($('bcHoras').value)*60+Number($('bcMinutos').value);if(m<30||m%30)return $('bcMsg').textContent='Use no mínimo 30 minutos, em blocos de 30.';try{const r=await provider.requestBankCorrection({competencia:$('bcComp').value,data_servico:$('bcData').value,minutos_solicitados:m,classe:$('bcClasse').value,descricao:$('bcDescricao').value});e.target.reset();$('bcHoras').value=0;$('bcMinutos').value=30;$('bcMsg').textContent=`Solicitação enviada. Protocolo ${r.id}.`;banco()}catch(x){$('bcMsg').textContent=x.message}};
['pmData','pmTurno','pmExtra'].forEach(i=>$(i).onchange=candidatos);$('formPermuta').onsubmit=async e=>{e.preventDefault();if(!$('pmTermo').checked)return $('pmMsg').textContent='Marque CONCORDO COM OS TERMOS.';const d={data:$('pmData').value,turno:$('pmTurno').value,servico_extra:Number($('pmExtra').value),substituto_id:Number($('pmSubstituto').value),substituto_nome:$('pmSubstituto').selectedOptions[0]?.textContent||'',observacao:$('pmObs').value,concordou_termo:true};try{editPermuta?await provider.updatePermutaRequest(editPermuta,d):await provider.requestPermuta(d);editPermuta=0;e.target.reset();$('pmCancelarEdicao').classList.add('hidden');$('pmMsg').textContent='Solicitação registrada.';permutas()}catch(x){$('pmMsg').textContent=x.message}};$('pmCancelarEdicao').onclick=()=>{editPermuta=0;$('formPermuta').reset();$('pmCancelarEdicao').classList.add('hidden')};
$('formMensagemComando').onsubmit=async e=>{e.preventDefault();try{await provider.sendInstitutionalMessage({titulo:$('msgTitulo').value,mensagem:$('msgConteudo').value,destino:$('msgDestino').value,guarda_ids:[...$('msgGcms').selectedOptions].map(x=>Number(x.value))});e.target.reset();$('msgComandoRetorno').textContent='Mensagem institucional enviada.'}catch(x){$('msgComandoRetorno').textContent=x.message}};$('msgDestino').onchange=()=>{$('msgGcmsLabel').classList.toggle('hidden',$('msgDestino').value!=='SELECIONADOS')};$('abrirAbastecimento').onclick=()=>abrirModulo('abastecimentos');$('abrirManutencao').onclick=()=>abrirModulo('manutencoes');$('onlineVoltar').onclick=()=>view('viaturas');
iniciar();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=100035',{updateViaCache:'none'}).catch(()=>{});
