
import {AuthenticatedProvider} from './data-provider.js';
import {MODULOS_GCMBS} from './access-catalog.js';
import {configurarPushNativo} from './native-push.js';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=d=>{if(!d)return'';const [y,m,day]=String(d).slice(0,10).split('-');return `${day}/${m}/${y}`},horas=min=>{const n=Number(min||0),sg=n<0?'-':'';return `${sg}${Math.floor(Math.abs(n)/60)}h${String(Math.abs(n)%60).padStart(2,'0')}`};
let provider=new AuthenticatedProvider(),onlineCatalog=[],onlineCurrent=null,onlineRecords=[],onlineEditing=null,quadroAtual=null;
const normalizar=v=>String(v??'').trim().toUpperCase().normalize('NFD').replace(/[\u0300-\u036f]/g,''),hoje=()=>new Date().toISOString().slice(0,10);
function setView(id){document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('hidden',x.dataset.view!==id));document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.go===id));if(id==='inicio')carregarQuadro();if(id==='escala')renderEscalas();if(id==='permutas')renderPermutas();if(id==='banco')renderBanco();if(id==='viaturas')renderViaturas();if(id==='outros')renderModulos();}
function temAcesso(m){if(m==='perfil'||m==='avisos')return true;if(m==='escalas')return provider.pode('escalas')||provider.pode('relatorios');if(m==='permutas')return provider.pode('permutas');if(m==='banco_horas')return provider.pode('banco_horas');return provider.pode(m)}
function aplicarPermissoes(){const mapa={inicio:null,escala:'escalas',viaturas:'viaturas',permutas:'permutas',banco:'banco_horas',outros:'perfil',avisos:'avisos',perfil:'perfil'};document.querySelectorAll('nav button').forEach(b=>{let ok=b.dataset.go==='inicio'||b.dataset.go==='outros'||temAcesso(mapa[b.dataset.go]);if(b.dataset.go==='viaturas')ok=temAcesso('abastecimentos')||temAcesso('manutencoes')||temAcesso('relatorios_frota');b.classList.toggle('hidden',!ok)});}
function minhasEscalas(){return provider.escalas().slice().sort((a,b)=>String(a.data).localeCompare(String(b.data)))}function meuBanco(){return provider.bancoHoras().filter(x=>String(x.status||'ATIVO').toUpperCase()==='ATIVO')}
function renderPerfil(){const s=provider.session||{};$('perfilNome').textContent=s.nome||'';$('perfilCargo').textContent=s.cargo||s.role||'';$('perfilUsuario').textContent=s.usuario||s.username||'';$('perfilRole').textContent=s.role||'gcm';const ps=provider.permissoesEfetivas();$('listaPermissoes').innerHTML=provider.controleTotal()?`<span class="badge">CONTROLE TOTAL · ${ps.length} módulos</span>`:ps.map(p=>`<span class="badge">${esc(p.modulo)} · ${esc(p.nivel)}</span>`).join(' ')||'<span class="muted">Sem permissões habilitadas no Desktop.</span>';}
const ocultosOutros=new Set(['dashboard','gerenciar_escalas','escalas','relatorios','banco_horas','permutas','abastecimentos','manutencoes','relatorios_frota']);
function renderModulos(){const el=$('listaModulos'),lista=provider.modulosAutorizados().filter(m=>!ocultosOutros.has(m.id));if(!lista.length){el.innerHTML='<div class="empty">Nenhum outro módulo autorizado.</div>';return}el.innerHTML=lista.map(m=>{const online=onlineCatalog.some(c=>c.modulo===m.id),acao=online?`<button class="mini" data-open-module="${esc(m.id)}">Abrir</button>`:'<span class="muted module-state">Autorizado</span>';return `<article class="module-card ready"><div><strong>${esc(m.nome)}</strong><small>${esc(m.descricao)}</small></div><span class="level">${esc(m.nivel)}</span>${acao}</article>`}).join('');document.querySelectorAll('[data-open-module]').forEach(b=>b.onclick=()=>abrirModuloOnline(b.dataset.openModule));}
async function aplicarIdentidadeVisual(){try{const r=await fetch('./data/branding.json',{cache:'no-store'});if(!r.ok)return;const b=await r.json(),icon=b?.icone?.arquivo||'icon.png';['loginIcone','headerIcone'].forEach(id=>{const el=$(id);if(el)el.src=icon})}catch{}}
async function aplicarIdentidadeVisualRemota(){try{const lista=await provider.branding(),icon=lista.find(x=>x.finalidade==='ICONE_APP')||lista[0];if(icon?.data_url)['loginIcone','headerIcone'].forEach(id=>{const el=$(id);if(el)el.src=icon.data_url})}catch{}}
function renderInicio(){const s=provider.session||{};$('perfilNome').textContent=s.nome||'';$('perfilCargo').textContent=s.cargo||s.role||'';}
function detalhesQuadro(c){const[g,k]=String(c||'').split('.');if(!quadroAtual)return[];if(g==='efetivo')return quadroAtual.efetivo?.detalhes?.[k]||[];if(g==='viaturas')return quadroAtual.viaturas?.detalhes?.[k]||[];if(g==='postos')return quadroAtual.postos?.detalhamento||[];return[]}
function abrirQuadroDetalhe(t,c){const itens=detalhesQuadro(c);$('quadroModalTitulo').textContent=t;$('quadroModalMeta').textContent=`${fmt(quadroAtual?.data)} · ${itens.length} registro(s)`;$('quadroModalLista').innerHTML=itens.map(x=>`<div class="item"><strong>${esc(x.nome||'-')}</strong><span>${esc(x.complemento||'')}</span></div>`).join('')||'<div class="empty">Nenhum registro.</div>';$('quadroModal').classList.remove('hidden')}
async function carregarQuadro(){if(!$('quadroData'))return;const data=$('quadroData').value||hoje();try{const d=await provider.quadro(data);quadroAtual=d;[['qAtivos',d.efetivo?.ativos],['qAfastados',d.efetivo?.afastados],['qFerias',d.efetivo?.feristas],['qServicoA',d.efetivo?.servicoA],['qServicoB',d.efetivo?.servicoB],['qViaturasTotal',d.viaturas?.total],['qViaturasDisponiveis',d.viaturas?.disponivel],['qViaturasUso',d.viaturas?.emUso],['qViaturasBaixadas',d.viaturas?.baixadas],['qViaturasManut',d.viaturas?.manutencao],['qPostos',d.postos?.cobertos]].forEach(([id,v])=>$(id).textContent=v||0);$('qAviso').textContent=(d.cnhVencidas||[]).length?`⚠ CNH vencida: ${d.cnhVencidas.length} GCM(s).`:'Quadro Operacional atualizado.'}catch(e){$('qAviso').textContent=e.message}}
function horarioRelatorio(x){const hi=String(x.horario_inicio||x.hist_horario_inicio||'').slice(0,5),hf=String(x.horario_fim||x.hist_horario_fim||'').slice(0,5);if(hi&&hf)return `${hi} às ${hf}`;return String(x.turno).toUpperCase()==='B'?'19:00 às 07:00':'07:00 às 19:00'}function nomeEscala(x){return x.nome_guerra||x.hist_guarda_nome_guerra||x.guarda_nome||x.guarda||'GCM'}function postoEscala(x){return String(x.posto_nome||x.hist_posto_nome||x.posto||'').trim()}
function gerarDatas(i,f){const a=[];if(!i||!f||f<i)return a;for(let d=new Date(i+'T00:00:00Z'),z=new Date(f+'T00:00:00Z');d<=z;d.setUTCDate(d.getUTCDate()+1))a.push(d.toISOString().slice(0,10));return a}
function renderEscalas(){const dados0=provider.escalas(),nomes=[...new Set(dados0.map(nomeEscala).filter(Boolean))].sort(),postos=[...new Set(dados0.map(postoEscala).filter(Boolean))].sort();$('escalaGcm').innerHTML='<option value="">Todos os GCMs</option>'+nomes.map(x=>`<option>${esc(x)}</option>`).join('');$('escalaPosto').innerHTML='<option value="">Todos os postos</option>'+postos.map(x=>`<option>${esc(x)}</option>`).join('');const ini=$('escalaIni').value,fim=$('escalaFim').value,g=$('escalaGcm').dataset.value||'',p=$('escalaPosto').dataset.value||'',h=$('escalaHorario').value;if(!ini||!fim)return;const dados=dados0.filter(x=>{const d=String(x.data||'').slice(0,10);return d>=ini&&d<=fim&&(!g||normalizar(nomeEscala(x))===normalizar(g))&&(!p||normalizar(postoEscala(x))===normalizar(p))&&(!h||horarioRelatorio(x)===h)}),datas=gerarDatas(ini,fim),map=new Map();for(const x of dados){const posto=postoEscala(x),hor=horarioRelatorio(x),k=posto+'\0'+hor;if(!map.has(k))map.set(k,{posto,hor,itens:new Map()});const arr=map.get(k).itens.get(x.data)||[];arr.push(nomeEscala(x));map.get(k).itens.set(x.data,arr)}$('cabecalhoMatrizMobile').innerHTML='<th>POSTO / HORÁRIO</th>'+datas.map(fmt).map(d=>`<th>${d}</th>`).join('');$('resultadoMatrizMobile').innerHTML=[...map.values()].map(r=>`<tr><th><b>${esc(r.posto)}</b><span>${esc(r.hor)}</span></th>${datas.map(d=>`<td>${(r.itens.get(d)||[]).map(n=>`<b>${esc(n)}</b>`).join('<br>')||'—'}</td>`).join('')}</tr>`).join('')||'<tr><td>Nenhuma escala encontrada.</td></tr>';$('escalaInfo').textContent=`${dados.length} registro(s) · ${fmt(ini)} a ${fmt(fim)}`;}
function statusSolic(r){const st=String(r.status||'').toUpperCase();if(st==='PROCESSADO'){const resp=String(r.resposta||'').toUpperCase();if(resp.includes('RECUS'))return'RECUSADA';if(resp.includes('APROV'))return'APROVADA'}return st==='PENDENTE_DESKTOP'?'PENDENTE':st}
function renderBanco(){const b=meuBanco();let c50=0,c100=0,d=0;for(const x of b){const s=String(x.natureza).toUpperCase()==='DEBITO'?-1:1,m=s*Number(x.minutos||0);if(s<0)d+=Number(x.minutos||0);if(String(x.classe)==='100')c100+=m;else c50+=m}$('bh50').textContent=horas(c50);$('bh100').textContent=horas(c100);$('bhDeb').textContent=horas(d);$('bhSaldo').textContent=horas(c50+c100);$('listaBanco').innerHTML=b.slice(0,40).map(x=>`<div class="item"><small>${fmt(x.data_fato)} · ${esc(x.classe||'50')}%</small><strong>${esc(x.tipo||x.origem||'Movimentação')}</strong><span>${String(x.natureza).toUpperCase()==='DEBITO'?'-':'+'}${horas(x.minutos)}</span></div>`).join('')||'<div class="empty">Sem movimentações.</div>';const req=provider.actionRequests().filter(x=>x.tipo==='BANCO_HORAS_CORRECAO');$('listaCorrecoes').innerHTML=req.map(r=>`<div class="item"><small>${fmt(r.payload?.data_servico)} · ${horas(r.payload?.minutos_solicitados)} · ${esc(r.payload?.classe||'50')}%</small><strong>${esc(r.payload?.descricao||'Solicitação')}</strong><span class="request-status">${esc(statusSolic(r))}</span>${r.resposta?`<small>${esc(r.resposta)}</small>`:''}</div>`).join('')||'<div class="empty">Nenhuma solicitação enviada.</div>';}
function renderPermutas(){const req=provider.actionRequests().filter(x=>x.tipo==='PERMUTA'),perms=provider.permutas();$('listaPermutas').innerHTML=[...req.map(r=>{const st=statusSolic(r),pend=st==='PENDENTE',p=r.payload||{};return `<div class="item"><small>${fmt(p.data)} · Turno ${esc(p.turno||'-')}</small><strong>Substituto: ${esc(p.substituto_nome||'A definir')}</strong><span>${esc(st)}</span>${r.resposta?`<small>${esc(r.resposta)}</small>`:''}${pend?`<div><button class="mini" data-pm-edit="${r.id}">Editar</button> <button class="mini" data-pm-del="${r.id}">Excluir</button></div>`:''}</div>`}),...perms.map(p=>`<div class="item"><small>${fmt(p.data)} · Turno ${esc(p.turno||'-')}</small><strong>${esc(p.substituido_nome||'GCM')} → ${esc(p.substituto_nome||'GCM')}</strong><span>${esc(p.status||'')}</span>${p.motivo_decisao?`<small>${esc(p.motivo_decisao)}</small>`:''}</div>`)].join('')||'<div class="empty">Nenhuma permuta.</div>';document.querySelectorAll('[data-pm-del]').forEach(b=>b.onclick=async()=>{if(confirm('Excluir esta solicitação pendente?')){try{await provider.cancelPermutaRequest(Number(b.dataset.pmDel));renderPermutas()}catch(e){alert(e.message)}}});document.querySelectorAll('[data-pm-edit]').forEach(b=>b.onclick=()=>{const r=req.find(x=>Number(x.id)===Number(b.dataset.pmEdit));if(!r)return;const p=r.payload||{};$('pmRequestId').value=r.id;$('pmData').value=p.data||'';$('pmTurno').value=p.turno||'A';$('pmExtra').value=String(p.servico_extra||0);$('pmObs').value=p.observacao||'';$('pmTermo').checked=!!p.concordou_termo;carregarSubstitutos();});}
async function carregarSubstitutos(){const data=$('pmData').value,turno=$('pmTurno').value,extra=Number($('pmExtra').value);$('pmSubstituto').innerHTML='<option>Carregando...</option>';try{const r=await provider.call('permutation_candidates',{data,turno,servico_extra:extra});$('pmSubstituto').innerHTML='<option value="">Selecione</option>'+(r.candidates||[]).map(x=>`<option value="${x.guarda_id}">${esc(x.nome_guerra)}</option>`).join('')}catch(e){$('pmSubstituto').innerHTML=`<option>${esc(e.message)}</option>`}}
async function renderViaturas(){const cards=[];for(const [mod,titulo] of [['abastecimentos','Abastecimento'],['manutencoes','Manutenção'],['relatorios_frota','Relatórios da Frota']])if(temAcesso(mod)&&!(mod==='relatorios_frota'&&!provider.gestor()))cards.push(`<article class="module-card ready"><div><strong>${titulo}</strong><small>Módulo autorizado</small></div><button class="mini" data-open-module="${mod}">Abrir</button></article>`);$('listaViaturas').innerHTML=cards.join('')||'<div class="empty">Nenhum módulo de viaturas autorizado.</div>';document.querySelectorAll('#listaViaturas [data-open-module]').forEach(b=>b.onclick=()=>abrirModuloOnline(b.dataset.openModule));}
function renderAvisos(){const n=provider.notifications();$('listaAvisos').innerHTML=n.map(x=>`<div class="item"><small>${esc(x.tipo||'AVISO')} · ${esc(x.criado_em||'')}</small><strong>${esc(x.titulo||'Aviso')}</strong><span>${esc(x.mensagem||'')}</span></div>`).join('')||'<div class="empty">Sem notificações.</div>';$('mensagemComando').classList.toggle('hidden',!provider.gestor())}
function renderTudo(){renderPerfil();renderInicio();renderBanco();renderPermutas();renderAvisos();aplicarPermissoes();renderModulos();}
function valorOnline(v){if(v==null)return'';return typeof v==='object'?JSON.stringify(v):String(v)}let onlineModuleFilter='';function renderCatalogoOnline(){const lista=onlineModuleFilter?onlineCatalog.filter(c=>c.modulo===onlineModuleFilter):onlineCatalog;$('onlineEntidades').innerHTML=lista.map(c=>`<article class="module-card ready" data-online-entity="${esc(c.entity)}"><div><strong>${esc(c.titulo)}</strong><small>${esc(c.modulo)}</small></div></article>`).join('');document.querySelectorAll('[data-online-entity]').forEach(x=>x.onclick=()=>abrirEntidadeOnline(x.dataset.onlineEntity))}async function carregarOnlineCatalog(){try{onlineCatalog=await provider.entityCatalog();renderCatalogoOnline();renderModulos()}catch{}}
function abrirModuloOnline(m){onlineModuleFilter=m;setView('online');renderCatalogoOnline()}async function abrirEntidadeOnline(e){const b=await provider.entityList(e,500,0);onlineCurrent=b.catalog;onlineRecords=b.records||[];$('onlineTitulo').textContent=onlineCurrent.titulo;$('onlineEntidades').closest('.card').classList.add('hidden');$('onlineRegistrosCard').classList.remove('hidden');renderRegistrosOnline()}function renderRegistrosOnline(){$('onlineRegistros').innerHTML=onlineRecords.map(r=>`<div class="item">${Object.entries(r.data||{}).filter(([k])=>!/_id$|^id$|dados/i.test(k)).slice(0,12).map(([k,v])=>`<small><b>${esc(k)}</b>: ${esc(valorOnline(v))}</small>`).join('')}</div>`).join('')||'<div class="empty">Nenhum registro.</div>'}
async function boot(){await aplicarIdentidadeVisual();const s=await provider.restore();if(s){$('loginTela').classList.add('hidden');$('appTela').classList.remove('hidden');$('quadroData').value=hoje();renderTudo();await Promise.all([carregarOnlineCatalog(),aplicarIdentidadeVisualRemota(),carregarQuadro()]);configurarPushNativo(provider).catch(()=>{})}}
$('loginForm').onsubmit=async e=>{e.preventDefault();try{await provider.login($('loginUsuario').value,$('loginSenha').value);$('loginTela').classList.add('hidden');$('appTela').classList.remove('hidden');$('quadroData').value=hoje();renderTudo();await Promise.all([carregarOnlineCatalog(),carregarQuadro()])}catch(x){$('loginErro').textContent=x.message}};$('sair').onclick=async()=>{await provider.logout();location.reload()};document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>setView(b.dataset.go));$('quadroData').onchange=carregarQuadro;document.querySelectorAll('[data-quadro-detail]').forEach(b=>b.onclick=()=>abrirQuadroDetalhe(b.dataset.title,b.dataset.quadroDetail));$('quadroModalFechar').onclick=()=>$('quadroModal').classList.add('hidden');$('escalaGerar').onclick=renderEscalas;
$('formBancoCorrecao').onsubmit=async e=>{e.preventDefault();const min=Number($('bcHoras').value)*60+Number($('bcMinutos').value);if(min<30||min%30)return $('bcMsg').textContent='Use no mínimo 30 minutos, em blocos de 30.';try{const r=await provider.requestBankCorrection({competencia:$('bcComp').value,data_servico:$('bcData').value,minutos_solicitados:min,classe:$('bcClasse').value,descricao:$('bcDescricao').value});e.target.reset();$('bcHoras').value=0;$('bcMinutos').value=30;$('bcMsg').textContent=`Solicitação enviada com sucesso. Protocolo ${r.id}.`;renderBanco()}catch(x){$('bcMsg').textContent=x.message}};
['pmData','pmTurno','pmExtra'].forEach(id=>$(id).onchange=carregarSubstitutos);$('formPermuta').onsubmit=async e=>{e.preventDefault();if(!$('pmTermo').checked)return $('pmMsg').textContent='É obrigatório aceitar o Termo de Responsabilidade.';const d={data:$('pmData').value,turno:$('pmTurno').value,servico_extra:Number($('pmExtra').value),substituto_id:Number($('pmSubstituto').value),substituto_nome:$('pmSubstituto').selectedOptions[0]?.textContent||'',observacao:$('pmObs').value,concordou_termo:true};try{const id=Number($('pmRequestId').value);const r=id?await provider.updatePermutaRequest(id,d):await provider.requestPermuta(d);e.target.reset();$('pmRequestId').value='';$('pmMsg').textContent=`Solicitação ${id?'atualizada':'enviada'} com sucesso. Protocolo ${r.id||id}.`;renderPermutas()}catch(x){$('pmMsg').textContent=x.message}};
$('formMensagem').onsubmit=async e=>{e.preventDefault();try{await provider.sendInstitutionalMessage({titulo:$('msgTitulo').value,mensagem:$('msgConteudo').value,destino:$('msgDestino').value});e.target.reset();$('msgRetorno').textContent='Mensagem institucional enviada.'}catch(x){$('msgRetorno').textContent=x.message}};
boot();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=100035',{updateViaCache:'none'}).catch(()=>{});
